version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: testfligoo-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-db:
    image: postgres:latest
    container_name: airflow-db
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata_airflow:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.6.0
    depends_on:
      - airflow-db
    container_name: airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__FERNET_KEY=${AF_FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    entrypoint: >
      /bin/bash -c "
      airflow db init &&
      airflow users create -u ${AIRFLOW_USER} -p ${AIRFLOW_USER_PW} -f ${AIRFLOW__F} -l ${AIRFLOW__L} -r ${AIRFLOW_R} -e ${AIRFLOW_E}
      "

  airflow:
    image: apache/airflow:2.6.0
    depends_on:
      - airflow-db
      - airflow-init
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__FERNET_KEY=${AF_FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/dags
      - AIRFLOW__CORE__PLUGINS_FOLDER=/usr/local/airflow/plugins
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/usr/local/airflow/logs
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_DAG=${POSTGRES_HOST_DAG}
      - ACCESS_KEY_API=${ACCESS_KEY_API}
      - ENDPOINT_API=${ENDPOINT_API}
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/logs:/usr/local/airflow/logs
      - ./airflow/plugins:/usr/local/airflow/plugins
      - ./airflow.cfg:/usr/local/airflow/airflow.cfg
    command: ["webserver"]

  airflow-scheduler:
    image: apache/airflow:2.6.0
    depends_on:
      - airflow-db
      - airflow-init
      - airflow
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__FERNET_KEY=${AF_FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/dags
      - AIRFLOW__CORE__PLUGINS_FOLDER=/usr/local/airflow/plugins
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/usr/local/airflow/logs
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_DAG=${POSTGRES_HOST_DAG}
      - ACCESS_KEY_API=${ACCESS_KEY_API}
      - ENDPOINT_API=${ENDPOINT_API}
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/logs:/usr/local/airflow/logs
      - ./airflow/plugins:/usr/local/airflow/plugins
      - ./airflow.cfg:/usr/local/airflow/airflow.cfg
    command: ["scheduler"]

  alembic:
    build: .
    depends_on:
      - postgres
      - airflow-scheduler
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  pgdata:
  pgdata_airflow:


