"""auto-generated migration

Revision ID: e77a863c0fbf
Revises: 
Create Date: 2024-06-13 21:22:34.643815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77a863c0fbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testdata',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flightDate', sa.Date(), nullable=False),
    sa.Column('flightStatus', sa.String(length=12), nullable=True),
    sa.Column('departureAirport', sa.String(length=50), nullable=True),
    sa.Column('departureTimezone', sa.String(length=50), nullable=True),
    sa.Column('departureTerminal', sa.String(length=10), nullable=True),
    sa.Column('departureGate', sa.String(length=10), nullable=True),
    sa.Column('departureDelay', sa.Integer(), nullable=True),
    sa.Column('departureScheduled', sa.DateTime(), nullable=True),
    sa.Column('departureEstimated', sa.DateTime(), nullable=True),
    sa.Column('arrivalAirport', sa.String(length=50), nullable=True),
    sa.Column('arrivalTimezone', sa.String(length=50), nullable=True),
    sa.Column('arrivalTerminal', sa.String(length=10), nullable=True),
    sa.Column('arrivalGate', sa.String(length=10), nullable=True),
    sa.Column('arrivalBaggage', sa.String(length=10), nullable=True),
    sa.Column('arrivalDelay', sa.Integer(), nullable=True),
    sa.Column('arrivalScheduled', sa.DateTime(), nullable=True),
    sa.Column('arrivalEstimated', sa.DateTime(), nullable=True),
    sa.Column('airlineName', sa.String(length=50), nullable=True),
    sa.Column('flightNumber', sa.String(length=10), nullable=True),
    sa.Column('departureScheduledCordoba', sa.DateTime(), nullable=True),
    sa.Column('arrivalScheduledCordoba', sa.DateTime(), nullable=True),
    sa.Column('flightDuration', sa.String(length=20), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testdata')
    # ### end Alembic commands ###
